changelog: images update part2
CleverCloud/documentation pull request #210
Opened 2024-02-27 06:18 UTC by davlgd

## Describe your PR

I've added an entry to the new images update and changed default version supported by .Net in documentation at the same time.

2024-02-27 13:12 UTC, cnivolle submitted a review, later dismissed

2024-02-27 13:33 UTC, juliamrch requested changes
Nice update, added some suggestions to clarify what ad who performs the action (runtime, Clever Cloud). Feel free to suggest other versions.

2024-02-27 13:33 UTC, juliamrch commented on content/changelog/2024-02-27-images-update-part2.md
> +Earlier this month, we published [a first set of updates](/changelog/2024-02-02-images-update/) for Docker, Erlang, Go, Haskell, Ruby and Rust. Some days ago, we finished this work and all our images
```suggestion
Earlier this month, Clever Cloud published [a first set of updates](/changelog/2024-02-02-images-update/) for Docker, Erlang, Go, Haskell, Ruby and Rust. Some days ago, we finished this work and all runtime images are now up-to-date. This process occurred with no impact for our users. 
```

2024-02-27 13:33 UTC, juliamrch commented on static/partials/language-specific-deploy/dotnet.md
> +The default version used on Clever Cloud is `8.0`. You can change it by setting the `CC_DOTNET_VERSION` environment variable to `6.0`. No support will be provided for non-LTS and older versions.
```suggestion
The default version used on Clever Cloud is `8.0`. You can change it by setting the `CC_DOTNET_VERSION` environment variable to `6.0`. Clever Cloud doesn't provide support for non-LTS and older versions.
```

2024-02-27 13:33 UTC, juliamrch commented on static/partials/language-specific-deploy/dotnet.md
> +During deployment, the `SimpleFeedReader.csproj` file and the target framework `net8.0` are automatically detected. Then, the .NET project is published:
```suggestion
During deployment, the runtime automatically detects the `SimpleFeedReader.csproj` file and the target framework `net8.0`. Then, it publishes the .NET project:
```

2024-02-27 15:45 UTC, juliamrch submitted a review, later dismissed
Big fan of the `stay tuned` with the RSS link. Let's merge.

2024-02-27 15:48 UTC, davlgd commented
> Big fan of the `stay tuned` with the RSS link. Let's merge.

We need to wait @s0dyy review before merging

2024-02-27 15:48 UTC, juliamrch commented
waiting for @s0dyy to have a look before merging.

- [Changelog entry](http://doc-review-pr-210.cleverapps.io/changelog/2024-02-27-images-update-part2/)
-  [.NET variables](http://doc-review-pr-210.cleverapps.io/doc/reference/reference-environment-variables/#net)
- [.Net page update](http://doc-review-pr-210.cleverapps.io/doc/applications/dotnet/#net-version)

2024-03-08 10:43 UTC, s0dyy commented on content/changelog/2024-02-27-images-update-part2.md
> +.Net `8.0` version is now available and enabled by default for new applications. This value can be modified via [the `CC_DOTNET_VERSION` environment variable](/doc/reference/reference-environment-var
Same here, not very readable and everything is mixed up (dotnet, php, apm...).

I prefer something simpler, like :

Dotnet:

- Version 8 support
- CC_DOTNET_VERSION variable now created by default for each new Dotnet application

Java:
- Version bump to 1.47.1 (With Java 21 support)

2024-03-08 10:49 UTC, s0dyy commented on content/changelog/2024-02-27-images-update-part2.md
> +Next step of our big images overhaul is to bring our new strategy to build them into production. We're currently testing it, and preparing enhancements for multiples runtimes. Your applications will
No need to talk about it

2024-03-11 09:16 UTC, juliamrch commented on content/changelog/2024-02-27-images-update-part2.md
> +Next step of our big images overhaul is to bring our new strategy to build them into production. We're currently testing it, and preparing enhancements for multiples runtimes. Your applications will
Thanks for your review @s0dyy

2024-03-22 16:04 UTC, juliamrch commented
Hi @davlgd the `static/partials/language-specific-deploy/dotnet.md` file doesn't exist anymore in the codebase, I think you can resolve conflicts by simply adding the content you modified to `content/doc/applications/dotnet/_index.md`.

2024-03-28 06:22 UTC, davlgd commented
LGTM

2024-03-28 10:30 UTC, juliamrch approved these changes
Conflicts seem resolved. Nice update. Good to go imo

2024-03-28 10:31 UTC, merged