Add a third-party software section and move some stuff inside
CleverCloud/documentation pull request #220
Opened 2024-03-08 11:01 UTC by sebartyr

## Describe your PR

Add third-party section in log management page in order to put aside those which are not directly supported by Clever Cloud.

## Checklist

- [ ] My PR is related to an opened issue : #
- [ ] I've read the [contributing guidelines](../CONTRIBUTING.md)

## Reviewes
_Who should review these changes?_ @juliamrch @StevenLeRoux

2024-03-08 15:04 UTC, StevenLeRoux commented
Do you mind adding the current Logs API in the supported HTTPS section?

2024-03-11 09:25 UTC, juliamrch requested changes
Added some suggestions following Vale checks.

2024-03-11 09:25 UTC, juliamrch commented on content/doc/administrate/log-management.md
> +Community software is not directly supported by Clever Cloud. It is developed by our community. We do not garantee they will be free of problems.
```suggestion
Community software isn't directly supported by Clever Cloud. It's developed by our community. We don't  guarantee their maintenance or correct functioning.
```

2024-03-11 09:25 UTC, juliamrch commented on content/doc/administrate/log-management.md
> +You had better open issues on their Git repositories instead of contacting our support.
```suggestion
You are better off opening issues on their GitHub repositories than contacting Clever Cloud support.
```

2024-03-18 16:05 UTC, sebartyr commented
Hi @juliamrch 
I merged suggestions

2024-03-18 16:46 UTC, merged