Update CI/CD documentation
CleverCloud/documentation pull request #233
Opened 2024-03-28 12:03 UTC by juliamrch

## Describe your PR

_Summarize your changes here : explain what, how, and why. Be as explicict as you can on why your changes are needed and avoid implicit reasoning._

The CI/CD page have been converted into a section and the documentation have been updated.

This PR creates a sub level for the CI/CD section, with the following changes in the CI/CD section:

- A dedicated page for GitHub
- A dedicated page for GitLab with updated info for Heptapod
- A dedicated page for writing a custom CI/CD with the CLI with a link to predefined variables
- A new partial for mandatory CI/CD configuration 

Additionally, the CI/CD components catalog have been added to Heptapod features.

## Checklist

- [ ] My PR is related to an opened issue : #
- [x] I've read the [contributing guidelines](../CONTRIBUTING.md)

## Reviewes
_Who should review these changes?_ @

2024-03-29 14:03 UTC, davlgd requested changes
LGTM after some changes, great new pages, congrats 👏

2024-03-29 14:03 UTC, davlgd commented on content/doc/ci-cd/gitlab.md
> +- `APP_ID`: you app_id on Clever Cloud, find it at the top right in Clever Cloud Console, in your application tab.
```suggestion
- `APP_ID`: Find it at the top right in [Clever Cloud Console](https://console.clevercloud.com), in your application tab.
```

2024-03-29 14:03 UTC, davlgd commented on content/doc/ci-cd/gitlab.md
> +You can use pipeline components to deploy from a self-hosted GitLab instance, by including it as a project and mirroring the Pipeline repository. Follow [GitLab documentation](https://docs.gitlab.com
```suggestion
You can use pipeline components to deploy from a self-hosted GitLab instance, by including it as a project and mirroring the pipeline repository. Follow [GitLab documentation](https://docs.gitlab.com/ee/ci/components/#use-a-gitlabcom-component-in-a-self-managed-instance) to get full instructions.
```

2024-03-29 14:03 UTC, davlgd commented on content/doc/ci-cd/gitlab.md
> +The self-hosted GitLab service on Clever Cloud with [Heptapod](/doc/addons/heptapod) already hosts the components, you don't need to do any set up like you would in a self-hosted instance.
```suggestion
The self-hosted GitLab service on Clever Cloud with [Heptapod](/doc/addons/heptapod) already hosts the components, you don't need to do any set up like you would in a self-hosted instance:
```

2024-03-29 14:03 UTC, davlgd commented on layouts/shortcodes/content/ci-cd-configuration.md
> +Find it in your machine, usually in `~/.config/clever-cloud/clever-tools.json`, after [installing the CLI](/doc/CLI).
```suggestion
Find it in your machine, usually in `~/.config/clever-cloud/clever-tools.json`, after installing [Clever Tools](https://github.com/CleverCloud/clever-tools/).
```

2024-04-02 12:42 UTC, cnivolle approved these changes

2024-04-02 12:51 UTC, merged