Document usage of CC_HEALTH_CHECK_PATH in blue-green deployment.
CleverCloud/documentation pull request #294
Opened 2024-06-07 11:06 UTC by gervaisb

## Describe your PR

Blue-green deployment refer to `8080/` to test the health of the system. However, `CC_HEALTH_CHECK_PATH` is more powerful.

This PR will add a reference to the health check page from the blue-green one. And document the default behavior of this health check.

## Checklist

- [ ] My PR is related to an opened issue : #
- [x] I've read the [contributing guidelines](/CleverCloud/documentation/blob/main/CONTRIBUTING.md)

## Reviewers
@juliamrch , @cnivolle , @adumas37

2024-06-08 21:52 UTC, noisegrrrl requested changes

2024-06-08 21:52 UTC, noisegrrrl commented on content/doc/best-practices/blue-green.md
> +A new VM, let's call it *Blue* is created. The deployment is successful when there's no error in the build phase and the [deployment healtcheck](https://developers.clever-cloud.com/doc/develop/health
```suggestion
A new VM, let's call it *Blue* is created. The deployment is successful when there's no error in the build phase and the [deployment healtcheck](https://developers.clever-cloud.com/doc/develop/healthcheck/) is successful. And that's it, you will use the new version on production within seconds.
```

2024-06-08 21:52 UTC, noisegrrrl commented on layouts/shortcodes/content/url_healthcheck.md
> +When no envrionment variable is defined the default is to get the root path, `/`.
```suggestion
By default, when no environment variable is defined, the root path `/` will be checked.
```

2024-06-11 15:24 UTC, juliamrch commented on content/doc/best-practices/blue-green.md
> +A new VM, let's call it *Blue* is created. The deployment is successful when there's no error in the build phase and the [deployment healtcheck](https://developers.clever-cloud.com/doc/develop/health
```suggestion
A new VM, let's call it *Blue* is created. The deployment is successful when there's no error in the build phase and the [deployment healthcheck](https://developers.clever-cloud.com/doc/develop/healthcheck/) is successful. And that's it, you will use the new version on production within seconds.
```

2024-06-11 15:27 UTC, juliamrch commented on layouts/shortcodes/content/url_healthcheck.md
> +By default, when no environment variable is defined, the root path `/` will be checked.
Specify what checks the root path and which path is that: 
```suggestion
By default, when no environment variable is defined, the monitoring check your repository root path `/`.
```

2024-06-13 13:26 UTC, merged