Add Ports explanation to troubleshootingp page
CleverCloud/documentation pull request #309
Opened 2024-06-26 15:11 UTC by Kirbeerus

## Describe your PR

_Summarize your changes here : Explanation of the ports a user may see open when they try to scan their domain.

## Checklist

- [ ] My PR is related to an opened issue : #
- [ ] I've read the [contributing guidelines](/CleverCloud/documentation/blob/main/CONTRIBUTING.md)

## Reviewers
_Who should review these changes?_ @

2024-07-02 08:40 UTC, cnivolle requested changes

2024-07-02 08:40 UTC, cnivolle commented on content/doc/find-help/troubleshooting.md
> +{{% details title="A lot of port appear open after a scan of my domain" closed="true" %}}
```suggestion
{{% details title="There are a lot of open ports, according to a port scan." closed="true" %}}
```

2024-07-02 08:40 UTC, cnivolle commented on content/doc/find-help/troubleshooting.md
> +- Ports 1080 and 1081 : They are necessary for the reverse-proxy Sozu to be able to redirect traffic to your application. Port 1080 is for HTTP and 1081 for HTTPS
```suggestion
- Ports 1080 and 1081 : Those are necessary for the reverse-proxy Sōzu to be able to redirect traffic to your application. Port 1080 is for HTTP and 1081 for HTTPS
```

2024-07-03 09:15 UTC, juliamrch commented on content/doc/find-help/troubleshooting.md
> +- Port 9999 : Zabbix use this port to monitor the hypervisor.
Fix grammar and add link to Zabbix homepage, so readers know what we are talking about.

```suggestion
- Port 9999 : [Zabbix](https://www.zabbix.com) uses this port to monitor the hypervisor.
```

2024-07-03 09:20 UTC, juliamrch commented on content/doc/find-help/troubleshooting.md
> +- Ports 5000 to 6000 : The TCP redirection feature use these port to work. If you see the port in this range open but don't have the feature enabled, it means other app also present on the same hyper
```suggestion
- Ports 5000 to 6000 : The TCP redirection feature uses these ports to work. If you notice a port within this range open but have not enabled the feature, it indicates that another app on the same hypervisor is using it. The load balancer assigns a unique port to each app, ensuring that your app is securely isolated. You can be assured that other users cannot access your app through this port.
```

2024-07-03 09:22 UTC, juliamrch reviewed
Thank you for this addition, very much needed!

I've added some suggestions to fix grammar and add clarity around the TCP feature. Feel free to commit them directly or to modify them if needed.

2024-07-17 09:15 UTC, Kirbeerus commented
I have added the suggestions and corrected some mistakes, is it okay to merge?

2024-07-17 15:08 UTC, juliamrch approved these changes

2024-07-17 15:08 UTC, juliamrch commented on content/doc/find-help/troubleshooting.md
> +- Port 80 and 443 : Your app use these ports to receive HTTP and HTTPS traffic
```suggestion
- Port 80 and 443 : Your app uses these ports to receive HTTP and HTTPS traffic
```

2024-07-17 15:15 UTC, merged