Runtime software versioning data
CleverCloud/documentation pull request #324
Opened 2024-07-03 13:57 UTC by cnivolle

## Describe your PR

This PR adds a simple way to **manage available versions of software or runtime** deployed on Clever Cloud.

Yaml files are used to render the list of a runtime or add-on.

So far, on those are made (and the version numbers needs a review): 
- DB: MySQL, MongoDB, PostgreSQL
- Runtime: PHP, Python

## Checklist

- [ ] My PR is related to an opened issue : #
- [x] I've read the [contributing guidelines](/CleverCloud/documentation/blob/main/CONTRIBUTING.md)

2024-07-03 14:32 UTC, davlgd requested changes
It's a good first iteration for this, thanks for the great job on it!. Just some nitpicks

2024-07-03 14:32 UTC, davlgd commented on content/doc/applications/php/_index.md
> +The supported versions are {{< runtimes_versions PHP >}}.
```suggestion
The supported versions are: {{< runtimes_versions PHP >}}
```

2024-07-03 14:32 UTC, davlgd commented on content/doc/applications/python/_index.md
> +The supported versions are {{< runtimes_versions python >}}
```suggestion
The supported versions are: {{< runtimes_versions python >}}
```

2024-07-03 14:32 UTC, davlgd commented on content/doc/addons/mongodb/_index.md
> +### Supported Versions
```suggestion
### Supported versions
```

2024-07-03 14:32 UTC, davlgd commented on content/doc/addons/mysql/_index.md
> +### Supported Versions
```suggestion
### Supported versions
```

2024-07-03 14:32 UTC, davlgd commented on content/doc/addons/postgresql/_index.md
> +### Supported Versions
```suggestion
### Supported versions
```

2024-07-03 14:32 UTC, davlgd commented on content/doc/applications/php/_index.md
> +### Supported Versions
```suggestion
### Supported versions
```

2024-07-03 14:32 UTC, davlgd commented on content/doc/applications/python/_index.md
> +### Supported Versions
```suggestion
### Supported versions
```

2024-07-03 14:32 UTC, davlgd commented on static/partials/language-specific-deploy/php.md
> +Set the `CC_PHP_VERSION` environment variable to one of the following values: {{< runtimes_versions PHP >}}.
```suggestion
Set the `CC_PHP_VERSION` environment variable to one of the following values: {{< runtimes_versions PHP >}}
```

2024-07-03 15:15 UTC, davlgd submitted a review, later dismissed

2024-07-17 15:19 UTC, juliamrch requested changes
Branch needs to be rebased in order to comply with Hextra 0.8 version

2024-07-29 16:16 UTC, cnivolle commented
It has been rebased (🥵) and works with the last version of Hextra.

A few things needs to be done : 
- improve the UI a bit (comas, final dots etc.)
- do a pass on several product pages to make sure we don't miss any product versioning.

2024-07-30 10:52 UTC, juliamrch commented on .github/workflows/review-app.yml
> +      - name: Manage reveiw app
```suggestion
      - name: Manage review app
```

2024-07-30 10:56 UTC, juliamrch commented
Branch is updated and I resolved the few conflicts created this morning (oupsy). Shall we merge this or keep revamping the versioning system for all add-ons and runtimes, and then merge? I can take it from there if needed. What do you think?

2024-08-06 14:56 UTC, aurrelhebert reviewed
LGTM

2024-08-06 14:56 UTC, aurrelhebert commented on data/software_versions_shared_dedicated.yml
> +    - "v8.0"
```suggestion
    - "v8.0.36"
```

2024-08-06 14:56 UTC, aurrelhebert commented on data/software_versions_shared_dedicated.yml
> +    - "v8.0"
```suggestion
    - "v8.0.22"
```

2024-08-06 14:56 UTC, aurrelhebert commented on data/software_versions_shared_dedicated.yml
> +    - "v15"
```suggestion
    - "v15.7"
```

2024-08-06 14:56 UTC, aurrelhebert commented on data/software_versions_shared_dedicated.yml
> +#myDB
It misses Redis and Elasticsearch: 
elasticsearch: 
   dedicated:
       - "v7.17.10"
       - "v8.10.2"
 redis: 
   dedicated:
       - "v7.2.4"

2024-08-06 14:56 UTC, aurrelhebert commented on data/software_versions_shared_dedicated.yml
> +    - "v14"
```suggestion
    - "v14.12"
```

2024-08-06 14:56 UTC, aurrelhebert commented on data/software_versions_shared_dedicated.yml
> +    - "v13"
```suggestion
    - "v13.15"
```

2024-08-06 14:56 UTC, aurrelhebert commented on data/software_versions_shared_dedicated.yml
> +    - "v12"
```suggestion
    - "v12.19"
```

2024-08-06 14:56 UTC, aurrelhebert commented on data/software_versions_shared_dedicated.yml
> +    - "v11"
```suggestion
    - "v11.22"
```

2024-08-13 13:55 UTC, juliamrch commented
## Follow up work: 

### Add-ons

- [ ] Add add-ons versions data
  - [ ] Elastic
  - [ ] Redis 
- [ ] Replace with shortcodes

### Applications

- [ ] Add runtime versions data
  - [ ] .NET
  - [ ] Elixir
  - [ ] Java
- [ ] Replace with shortcodes in pages
- [ ] Rework partial to erase **Shared** when not needed in page

2024-08-16 14:58 UTC, juliamrch commented on layouts/shortcodes/software_versions_shared_dedicated.html
> +  {{ $.Page.RenderString "<!-- markdown -->{{< callout type=\"warning\">}}  <strong>Important</strong>: Dev plans are free and intended <u>solely for testing purposes</u>. They do not provide the sam
```suggestion
  {{ $.Page.RenderString "<!-- markdown -->{{< callout type=\"warning\">}}  <strong>Important</strong>: Dev plans are free and intended <u>solely for testing purposes</u>. They don't provide the same guarantees or SLAs as dedicated plans. {{< /callout >}}" | safeHTML }}
```

2024-08-16 14:59 UTC, juliamrch submitted a review, later dismissed
wonderful

2024-08-16 15:07 UTC, merged