Keycloak documentation : fix variables, hostnames, java flavor
CleverCloud/documentation pull request #334
Opened 2024-07-11 06:43 UTC by please-openit

## Describe your PR

Keycloak documentation up to date with all supported variables and features

2024-07-11 13:08 UTC, allemas commented on content/doc/addons/keycloak.md
> +- S Java
We are still in XS

2024-07-11 13:11 UTC, allemas commented
LGTM for me except for the java size runtime.

2024-07-16 14:50 UTC, davlgd requested changes
Some edits, if you're ok with this, I'll check the final layout and merge

2024-07-16 14:50 UTC, davlgd commented on content/doc/addons/keycloak.md
> +    - In the Java application, you can explicitly Realms (separated each of them with `,`) you want to export as arguments to the `CC_KEYCLOAK_EXPORT_REALMS` environment variable;
```suggestion
    - In the Java application, you can explicitly declare Realms (separated each of them with `,`) you want to export as arguments to the `CC_KEYCLOAK_EXPORT_REALMS` environment variable;
```

2024-07-16 14:50 UTC, davlgd commented on content/doc/addons/keycloak.md
> +## Exporting realms data
```suggestion
### Exporting realms data
```

2024-07-16 14:50 UTC, davlgd commented on content/doc/addons/keycloak.md
> +2 specific authentication flows with a filter based on IP Addresses we made especially for you has been created and affected as default to clients "security-admin-console" and "admin-cli".
```suggestion
Two specific authentication flows with an IP addresses based filter are especially created and affected as default to clients "security-admin-console" and "admin-cli". To use them: 
```

2024-07-16 14:50 UTC, davlgd commented on content/doc/addons/keycloak.md
> +## Importing realms data
I think we should place this in the `Realms managment` section and move plugins/themes stuff outside of it. 

```suggestion
### Importing realms data
```

2024-07-16 14:50 UTC, davlgd commented on content/doc/addons/keycloak.md
> +
```suggestion
- Enable "PLEASE-OPEN.IT Authenticator IP Range" to "Required".
- Click on the crank to access parameters
- Set IPs with authorized access

**Do not forget to make the same on each realm you want to protect.**

```

2024-07-16 14:50 UTC, davlgd commented on content/doc/addons/keycloak.md
> +By default, your Keycloak instance is expose through a Clever-Cloud addon domain, avaible in the addon dashboard.
```suggestion
By default, your Keycloak instance is exposed through a Clever Cloud service domain, as mentioned in the `Service dependencies` tab of your add-on.
```

2024-07-16 14:50 UTC, davlgd commented on content/doc/addons/keycloak.md
> +Change the variable `CC_KEYCLOAK_HOSTNAME`, then restart your Java runtime.
```suggestion
You can use your own domain. [Just set it](/doc/administrate/domain-names/) in the `Domains` section of the Java application of the Keycloak add-on. Then, edit the `CC_KEYCLOAK_HOSTNAME` environment variable, apply this change and restart the application.
```

2024-07-16 14:50 UTC, davlgd commented on content/doc/addons/keycloak.md
> +Keycloak can expose administration console on a different hostname. By default, we use the same hostname, define `CC_KEYCLOAK_HOSTNAME_ADMIN` variable then restart your Java runtime to get a specific
```suggestion
By default, Keycloak expose administration console on the same hostname but [you can use another one](https://www.keycloak.org/server/hostname#_exposing_the_administration_console_on_a_separate_hostname). Add its domain to the application and set it through the `CC_KEYCLOAK_HOSTNAME_ADMIN` environment variable. Then apply this change and restart the application.
```

2024-07-16 14:50 UTC, davlgd commented on content/doc/addons/keycloak.md
> +> Don’t forget to apply change at the bottom of the environment variable page if you use the console.
This is more a Clever Cloud Console rule, not specific to Keycloak add-on

```suggestion
```

2024-07-16 14:50 UTC, davlgd commented on content/doc/addons/keycloak.md
> +> Don’t forget to apply change at the bottom of the environment variable page if you use the console.
```suggestion
```

2024-07-16 14:50 UTC, davlgd commented on content/doc/addons/keycloak.md
> +[https://www.keycloak.org/server/hostname#_exposing_the_administration_console_on_a_separate_hostname](https://www.keycloak.org/server/hostname#_exposing_the_administration_console_on_a_separate_host
```suggestion
```

2024-07-16 14:50 UTC, davlgd commented on content/doc/addons/keycloak.md
> +The admin interface is accessible on the `/admin` endpoint. The default user and password are provided in the Java application by the environment variables `CC_KEYCLOAK_ADMIN` and `CC_KEYCLOAK_ADMIN_
```suggestion
The admin interface is accessible on the `/admin` endpoint. The default user and password are provided in the Java application by the environment variables `CC_KEYCLOAK_ADMIN` and `CC_KEYCLOAK_ADMIN_DEFAULT_PASSWORD`. 

A password change is requested at the first connection.
```

2024-07-16 14:50 UTC, davlgd commented on content/doc/addons/keycloak.md
> +Your exported realm is available in `realms/export` folder in the associated FSBucket.
```suggestion
Your exported realm is available in `realms/export` folder in the associated FS Bucket.
```

2024-07-17 13:33 UTC, merged