Update Addon API documentation : Add test environment details
CleverCloud/documentation pull request #337
Opened 2024-07-16 12:31 UTC by allemas

## Describe your PR

In clever's internal functioning, if there is no test environment, the addon doesn't work properly. 

I've added a note to this subject in the document, specifying that if there is no test environment, the same thing must be entered as for “prod”.

2024-07-23 08:50 UTC, juliamrch commented
Hi @allemas, you can already check [the editorial linter warnings](https://github.com/CleverCloud/documentation/pull/337/files) related to this file to modify it.

2024-08-13 15:32 UTC, miton18 approved these changes

2024-09-06 12:48 UTC, juliamrch requested changes
Hi @allemas, 

I added two suggestions and another sentence needs to be clearer.

2024-09-06 12:48 UTC, juliamrch commented on content/doc/marketplace/_index.md
> +* `api/test/base_url` - The test endpoint on which Clever Cloud sends actions requests. Used to test your service when you create an add-on provider. After the add-on creation,`api/production/base_ur
"After the add-on creation,`api/production/base_url` is used" : by who or by what @allemas ?

```suggestion
* `api/test/base_url` - The test endpoint on which Clever Cloud sends actions requests. Use it to test your service when you create an add-on provider. After the add-on creation,`api/production/base_url` is used. If you're **not using** a test environment, set the same value as `api/production/base_url`.
```

2024-09-06 12:48 UTC, juliamrch commented on content/doc/marketplace/_index.md
> +* `api/test/sso_url` - The test endpoint for single sign-on. Used to test your service when you create an add-on provider. After that, the `api/production/sso_url` is used. If you're **not using** a
"the `api/production/sso_url` is used":  _idem_
```suggestion
* `api/test/sso_url` - The test endpoint for single sign-on. Use it to test your service when you create an add-on provider. After that, the `api/production/sso_url` is used. If you're **not using** a test environment, set the same value as 
```

2025-01-24 04:14 UTC, closed without merging

2025-01-24 04:14 UTC, juliamrch commented
No activity on this branch, no requested info provided, closed.