Add FAQ about add-on creation needing personal information
CleverCloud/documentation pull request #442
Opened 2024-11-19 15:35 UTC by Kirbeerus

## Describe your PR

Somme add-on need you to fill you account information to be able to create them.
Added a part in the FAQ about this.

## Checklist

- [ ] My PR is related to an opened issue : #
- [ ] I've read the [contributing guidelines](/CleverCloud/documentation/blob/main/CONTRIBUTING.md)

## Reviewers
_Who should review these changes?_ @

2024-11-26 16:35 UTC, cnivolle requested changes

2024-11-26 16:35 UTC, cnivolle commented on content/doc/find-help/faq.md
> +The creation of certain add-ons require you to fill the information of your account, such as the city, ZIP code, ect..
```suggestion
The creation of add-ons require you to fill the information of your account, such as the city, ZIP code, etc.
```

2024-12-02 13:24 UTC, Kirbeerus commented
@cnivolle Can you review the change you requested ? Otherwise, I can't launch the merge.

2024-12-02 13:50 UTC, cnivolle commented on content/doc/find-help/faq.md
> +The creation of add-ons require you to fill the information of your account, such as the city, ZIP code, etc.
```suggestion
To create add-ons, you need to complete your account information, including your city and ZIP code. 
```

2024-12-02 13:50 UTC, cnivolle commented on content/doc/find-help/faq.md
> +For example, you can't create a Matomo add-on if those information aren't present.
```suggestion
For instance, you cannot create a Matomo add-on until you provide these details.```

2024-12-02 14:30 UTC, cnivolle approved these changes

2024-12-02 14:30 UTC, merged