Nano pico priorities
CleverCloud/documentation pull request #456
Opened 2024-11-25 14:39 UTC by Dekabry

## Describe your PR

Added pico & nano callout mentionning they have lower priorities (and explaining why sometimes performance might drop).
Added a link from "Quickstart" to "Scalability" to better inform new users about instance sizes.

## Checklist

- [x] My PR is related to an opened issue : #48
- [x] I've read the [contributing guidelines](/CleverCloud/documentation/blob/main/CONTRIBUTING.md)

## Reviewers
@CleverCloud/reviewers

2024-11-25 14:56 UTC, Dekabry commented
@cnivolle  Nope, that was an accident, i pushed that one on another PR and i'm not sure why it pushed it it here as well.
I think i should have deleted my `haskell-variables` branch ?

2024-11-26 16:10 UTC, cnivolle commented
@Dekabry the callout should be above "Enable auto-scalability" for an easy reading.

2024-11-28 09:59 UTC, Kirbeerus commented
@Dekabry I just took a look at the review app, and i don't see the callout about Nano and Pico appear on the page `Application Scaling`.
Can you check if you also have the problem.

2024-11-28 10:26 UTC, Dekabry commented
@Kirbeerus  i see it right here from the review app ? 
![image](https://github.com/user-attachments/assets/c3ce09a0-0e45-477c-b9df-19c454a8a56a)

2024-11-28 10:41 UTC, Kirbeerus requested changes

2024-11-28 10:41 UTC, Kirbeerus commented on content/doc/quickstart/_index.md
> +  You can learn more about scaling & instances size [here](https://developers.clever-cloud.com/doc/administrate/scalability/).
```suggestion
  You can learn more about scaling & instances size [here](/doc/administrate/scalability).
```

2024-11-28 10:41 UTC, Kirbeerus commented on content/doc/quickstart/_index.md
> +  You can learn more about scaling & instances size [here](https://developers.clever-cloud.com/doc/administrate/scalability/).
Instead of using a link that directly send to the real documentation, use a reference to the doc.

2024-11-28 10:50 UTC, Kirbeerus approved these changes

2024-11-28 10:58 UTC, merged