Cellar ip restriction example
CleverCloud/documentation pull request #471
Opened 2024-12-12 15:03 UTC by Dekabry

## Describe your PR

Added an example for IP restriction policy on Cellar

## Checklist

- [x] My PR is related to an opened issue : #24
- [x] I've read the [contributing guidelines](/CleverCloud/documentation/blob/main/CONTRIBUTING.md)

## Reviewers
@CleverCloud/reviewers

2024-12-17 13:17 UTC, Dekabry commented
I thought I had stashed it :weary: 
I'll fix that

2024-12-17 16:22 UTC, cnivolle requested changes

2024-12-17 16:22 UTC, cnivolle commented on content/doc/addons/cellar.md
> +- Change the `Effect` to "`Allow` or `Deny` depending on your needs.
```suggestion
- Change the `Effect` to `Allow` or `Deny` depending on your needs.  
```

2024-12-30 15:13 UTC, cnivolle approved these changes

2024-12-30 15:13 UTC, merged