fix: upgrade hugo version, theme and fix 404 on image
CleverCloud/documentation pull request #474
Opened 2024-12-17 15:35 UTC by juliamrch

## Describe your PR

Maintenance PR for the site: 

- Upgrade to Hugo [0.139.5](https://github.com/gohugoio/hugo/releases/tag/v0.139.5) (no major changes)
- Upgrade to [Hextra v0.9.0](https://github.com/imfing/hextra/releases/tag/v0.9.0) (new callouts available)
- fix: 404 on an image 

## Checklist

- [ ] My PR is related to an opened issue : #
- [x] I've read the [contributing guidelines](/CleverCloud/documentation/blob/main/CONTRIBUTING.md)

## Reviewers
_Who should review these changes?_ @CleverCloud/reviewers

2024-12-17 16:38 UTC, cnivolle commented
@juliamrch The version v0.139.5 can't be downloaded. The release don't list the traditionnal 29 packages.

Here's the broken link: https://github.com/gohugoio/hugo/releases/download/v0.139.5/hugo_extended_0.139.5_Linux-64bit.tar.gz

The 0.140.0 will work tho. I've tried it locally.

2024-12-18 11:50 UTC, juliamrch commented
> > You updated . This content is also listed on external doc. Issue number has been created and assigned to you 🫵👁️👄👁️
> > See it or modify it here: *
> > _This unique comment uses the very cool [taoliujun/action-unique-comment](https://github.com/marketplace/actions/unique-comment). Thank you <3_
> 
> @juliamrch is this the bot of updated on content ? Look like it's messed up, maybe because of the migration.

absolutely, will push some fix

2025-01-07 12:38 UTC, davlgd commented on .github/workflows/review-app.yml
> +          GH_HUGO_VERSION: '0.140.0'
v0.9.3 and 0.140.2 are available, maybe we can update

2025-01-07 12:38 UTC, davlgd commented on hugo.yaml
> +    max: "0.139.5"
If we update the version, we should update this ? But I'm not sure it's mandatory as there is no [such requirements](https://gohugo.io/hugo-modules/configuration/#module-configuration-hugoversion) for Hextra ([only Extended](https://imfing.github.io/hextra/docs/getting-started/#prerequisites))

2025-01-13 10:02 UTC, juliamrch commented on .github/workflows/review-app.yml
> +          GH_HUGO_VERSION: '0.140.0'
Have it been tested? No breaking changes?

2025-01-13 10:43 UTC, cnivolle commented on .github/workflows/review-app.yml
> +          GH_HUGO_VERSION: '0.140.0'
lets update to 0.140 now and test later for 0.142. The 0.142 has no major or important updates.

2025-01-13 10:48 UTC, cnivolle requested changes

2025-01-13 10:48 UTC, cnivolle commented on hugo.yaml
> +    max: "0.139.5"
```suggestion
    max: "0.140.0"
```

2025-01-13 10:49 UTC, cnivolle approved these changes

2025-01-13 10:55 UTC, merged